# -*- coding: utf-8 -*-
"""
Created on Wed Jun 13 09:48:58 2018
@author: huimin
Modified by JiM in Feb 2019
Modified by Felicia July 2019 to function with Python 3 and removed unused commands
Modified by JiM to plot the result of a few tracks generated by "particle_track_using_fvcom.py"
"""
import numpy as np
import matplotlib.pyplot as plt
from pandas import read_csv,DataFrame

###HARDCODES####
date='Nov_25_Dec_8_2014'
filepath=''
m1=np.load('particle_track_using_fvcom_11_29b_2014.npy', encoding='bytes', allow_pickle=True)#FMP encoded and pickle for Python3 results of "particle_track_using_fvcom"
m2=np.load('particle_track_using_fvcom_11_25_2014.npy', encoding='bytes', allow_pickle=True)#FMP encoded and pickle for Python3 
m3=np.load('particle_track_using_fvcom_11_29_2014.npy', encoding='bytes', allow_pickle=True)#FMP encoded and pickle for Python
df=read_csv('/net/pubweb_html/drifter/drift_wbsnecwa_2014_1.dat',sep='\s*',header=None)
FN='necscoast_worldvec.dat' # coastline file
CL=np.genfromtxt(FN,names=['lon','lat'])
# extract drift into from df
dlat=df[8].values
dlon=df[7].values
did=df[0].values
dmon=df[2].values
dday=df[3].values
df1=DataFrame([did,dlon,dlat,dmon,dday]).T
fig=plt.figure(figsize=(17,7))
plt.subplots_adjust(wspace=0.08,hspace=0.1)
ax1=fig.add_subplot(1,2,1)  
ax1.plot(CL['lon'],CL['lat'],'b-')

# For each of the three drifters, plot model and observed path.
for k in range(3):
	if k==0:
		p=m1.tolist()
		df2=df1[df1[0]==140410703]# landed Jeremey Pt
		c='c'
	elif k==1:
		p=m2.tolist()
		df2=df1[df1[0]==140410701]# landed Sandy Neck
		c='m'
	else:
		p=m3.tolist()
		df2=df1[df1[0]==140410706]# landed Eastham in model
		df2=df2[0:100] # limited track to same 4 days of the model
		c='k'
	a=0
	ax1.plot(p[b'lon'][0][a][0:],p[b'lat'][0][a][0:],color=c)
	ax1.scatter(p[b'lon'][0][a][0],p[b'lat'][0][a][0],label='Start',color='green')
	ax1.scatter(p[b'lon'][0][a][-1],p[b'lat'][0][a][-1],label='End',color='red')
	ax1.plot(df2[1],df2[2],color=c,linestyle='dotted',linewidth=2)

#ax1.legend(loc='upper right',scatterpoints=1) 
ax1.set_xlim([-70.7,-69.9])
ax1.set_ylim([41.5,42.1]) 
ax1.set_title('GOM3',fontsize=16)
for tick in ax1.xaxis.get_major_ticks():  
    tick.label1.set_fontsize(13) 
for tick in ax1.yaxis.get_major_ticks():  
    tick.label1.set_fontsize(13) 
    
#plt.savefig('Fig14_CCB_ParticleTracks_GOM3_MassBay.eps',format='eps',dpi=400,bbox_inches='tight')
#plt.savefig('Fig14_CCB_ParticleTracks_GOM3_MassBay',dpi=400,bbox_inches='tight')
plt.show()
